package org.hotel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssetCollectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetCollectionAllPropertiesEquals(AssetCollection expected, AssetCollection actual) {
        assertAssetCollectionAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetCollectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetCollectionAllUpdatablePropertiesEquals(AssetCollection expected, AssetCollection actual) {
        assertAssetCollectionUpdatableFieldsEquals(expected, actual);
        assertAssetCollectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetCollectionAutoGeneratedPropertiesEquals(AssetCollection expected, AssetCollection actual) {
        assertThat(actual)
            .as("Verify AssetCollection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetCollectionUpdatableFieldsEquals(AssetCollection expected, AssetCollection actual) {
        assertThat(actual)
            .as("Verify AssetCollection relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetCollectionUpdatableRelationshipsEquals(AssetCollection expected, AssetCollection actual) {
        // empty method
    }
}
