package org.hotel.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hotel.domain.AssertUtils.bigDecimalCompareTo;

public class BookingItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingItemAllPropertiesEquals(BookingItem expected, BookingItem actual) {
        assertBookingItemAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingItemAllUpdatablePropertiesEquals(BookingItem expected, BookingItem actual) {
        assertBookingItemUpdatableFieldsEquals(expected, actual);
        assertBookingItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingItemAutoGeneratedPropertiesEquals(BookingItem expected, BookingItem actual) {
        assertThat(actual)
            .as("Verify BookingItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingItemUpdatableFieldsEquals(BookingItem expected, BookingItem actual) {
        assertThat(actual)
            .as("Verify BookingItem relevant properties")
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getOccupantName()).as("check occupantName").isEqualTo(expected.getOccupantName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingItemUpdatableRelationshipsEquals(BookingItem expected, BookingItem actual) {
        assertThat(actual)
            .as("Verify BookingItem relationships")
            .satisfies(a -> assertThat(a.getRoomType()).as("check roomType").isEqualTo(expected.getRoomType()))
            .satisfies(a -> assertThat(a.getAssignedRoom()).as("check assignedRoom").isEqualTo(expected.getAssignedRoom()))
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
