package org.hotel.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hotel.domain.AssertUtils.bigDecimalCompareTo;

public class RoomTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomTypeAllPropertiesEquals(RoomType expected, RoomType actual) {
        assertRoomTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertRoomTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomTypeAllUpdatablePropertiesEquals(RoomType expected, RoomType actual) {
        assertRoomTypeUpdatableFieldsEquals(expected, actual);
        assertRoomTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomTypeAutoGeneratedPropertiesEquals(RoomType expected, RoomType actual) {
        assertThat(actual)
            .as("Verify RoomType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomTypeUpdatableFieldsEquals(RoomType expected, RoomType actual) {
        assertThat(actual)
            .as("Verify RoomType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getBasePrice()).as("check basePrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBasePrice())
            )
            .satisfies(a -> assertThat(a.getMaxCapacity()).as("check maxCapacity").isEqualTo(expected.getMaxCapacity()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomTypeUpdatableRelationshipsEquals(RoomType expected, RoomType actual) {
        // empty method
    }
}
