package org.hotel.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hotel.domain.AssertUtils.bigDecimalCompareTo;

public class ServiceRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceRequestAllPropertiesEquals(ServiceRequest expected, ServiceRequest actual) {
        assertServiceRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceRequestAllUpdatablePropertiesEquals(ServiceRequest expected, ServiceRequest actual) {
        assertServiceRequestUpdatableFieldsEquals(expected, actual);
        assertServiceRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceRequestAutoGeneratedPropertiesEquals(ServiceRequest expected, ServiceRequest actual) {
        assertThat(actual)
            .as("Verify ServiceRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceRequestUpdatableFieldsEquals(ServiceRequest expected, ServiceRequest actual) {
        assertThat(actual)
            .as("Verify ServiceRequest relevant properties")
            .satisfies(a -> assertThat(a.getRequestDate()).as("check requestDate").isEqualTo(expected.getRequestDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()))
            .satisfies(a -> assertThat(a.getDeliveryRoomNumber()).as("check deliveryRoomNumber").isEqualTo(expected.getDeliveryRoomNumber())
            )
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getTotalCost()).as("check totalCost").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotalCost())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceRequestUpdatableRelationshipsEquals(ServiceRequest expected, ServiceRequest actual) {
        assertThat(actual)
            .as("Verify ServiceRequest relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()))
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
