package org.hotel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WebContentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebContentAllPropertiesEquals(WebContent expected, WebContent actual) {
        assertWebContentAutoGeneratedPropertiesEquals(expected, actual);
        assertWebContentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebContentAllUpdatablePropertiesEquals(WebContent expected, WebContent actual) {
        assertWebContentUpdatableFieldsEquals(expected, actual);
        assertWebContentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebContentAutoGeneratedPropertiesEquals(WebContent expected, WebContent actual) {
        assertThat(actual)
            .as("Verify WebContent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebContentUpdatableFieldsEquals(WebContent expected, WebContent actual) {
        assertThat(actual)
            .as("Verify WebContent relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getSubtitle()).as("check subtitle").isEqualTo(expected.getSubtitle()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getActionUrl()).as("check actionUrl").isEqualTo(expected.getActionUrl()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebContentUpdatableRelationshipsEquals(WebContent expected, WebContent actual) {
        assertThat(actual)
            .as("Verify WebContent relationships")
            .satisfies(a -> assertThat(a.getCollection()).as("check collection").isEqualTo(expected.getCollection()));
    }
}
